import type { Metadata } from "next";
import "./globals.css";
import { DashBoardView } from "@/modules/dashboard/DashBoardView";
import { AppProvider } from "@/store/ContextProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Pinspire",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/pinspire-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <AppProvider>

          <DashBoardView />
          <Toaster />
          {children}

        </AppProvider>
      </body>
    </html>
  );
}
